<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.0.0" />
		<PackageReference Include="Mapster" Version="7.4.0" />
		<PackageReference Include="MeraStore.Shared.Kernel.Persistence" Version="1.0.5" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeraStore.Services.User.Domain\MeraStore.Services.User.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\" />
  </ItemGroup>

</Project>
